Added Meeting Notes from Notion
cse-112-sp22-group1/cse112-sp22-group1 pull request #38
Opened 2022-06-01 09:49 UTC by Darin8

Exported each document from the meetings from Notion as markdown files.

Let me know if there are any other documents needed from Notion.

2022-06-02 22:57 UTC, forschoolandnothingelse requested changes

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Sprint 1 Review.md
> +-
Remove this bullet point

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 5 Product Meeting.md
> +-
Remove this bullet

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 5 Product Meeting.md
> +# Action items
Remove this section

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 6 Product Meeting.md
> +# What are we doing this week?
Remove this empty section

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 6 Product Meeting.md
> +-
Add "none"

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 7 Product Meeting.md
> +# What did we do last week?
Remove this

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 7 Product Meeting.md
> +# What are we doing this week?
Remove this

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 8 Product Meeting.md
> +# Agenda
Remove this section

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 8 Product Meeting.md
> +# Action items
Remove this section

2022-06-02 22:57 UTC, forschoolandnothingelse commented on admin-cse112/meeting/Week 9 Product Meeting.md
> +# Meeting Notes
Remove this section

2022-06-03 22:45 UTC, e5chang approved these changes
I agree about deleting any empty sections and keep useful/relevant comments. Otherwise looks good

2022-06-04 07:44 UTC, waynarbocangel approved these changes

2022-06-05 04:24 UTC, forschoolandnothingelse approved these changes
Thanks for making those changes.

2022-06-05 12:19 UTC, merged